### ISSUE TITLE
Discount Codes for child accounts not renewing when parent membership renews.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-sponsored-members#111]
**Describe the bug**
Child discount codes will always expire, and not renew upon parent account renewal. 

Code reference: https://github.com/strangerstudios/pmpro-sponsored-members/blob/dev/pmpro-sponsored-members.php#L243 (Removing this to let the code never expire should be okay)

**To Reproduce**
1. Signup for a parent account.
2. Set the expiration date of the code to a past date (to "spoof" the 1 year period)
3. Try checkout with the code. (Parent account/membership still active and valid)

**Expected behavior**
Proposed change is to set the discount code to never expire when created at parent checkout, as there are checks on registration that the parent account is active.

Code reference: https://github.com/strangerstudios/pmpro-sponsored-members/blob/dev/pmpro-sponsored-members.php#L713-L747

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by michaelbeil** [comment]
A customer (ticket 447249) is running into this:
>We have had a renewal of a membership who’s child members have dropped off again (all of them). They paid by invoice yesterday and then all their child member orders were changed to inactive, then a new order can be seen with no discount code and their level set to None. Screenshot attached. What is even worse is we have an event for sale on the website with cheaper prices if you are logged in as a member and people are going on the site and their child membership is no longer live when it should be (their child membership orders are canceled again. Even though the parent member renewed with payment by invoice).

**Comment by ipokkel** [comment]
Moderators Ony: #463233
