### ISSUE TITLE
sponsored members will lose the code_id when membership expires

### ISSUE THREAD

**Issue by heddesheimer** [strangerstudios/pmpro-sponsored-members#14]
I found a potential problem when a membership for a sponsored member expires. In this case PMP will set the membership to "none" and mark the active membership as inactive. When I go into the user management and re-activate the sponsored membership, it will no longer show up as a child of the parent member (who's coupon code was used).

Reason is, that PMP will create a new record in the pmpro_memberships_users table where the code_id is 0.

This means, you can't track where the member belongs to, after the membership expired.

**Comment by apsolut** [comment]
+1
