### ISSUE TITLE
Sponsor (Parent) accounts can checkout for a sponsored (child) account.

### ISSUE THREAD

**Issue by greathmaster** [strangerstudios/pmpro-sponsored-members#31]
Parent accounts are permitted to checkout for the Child accounts using their own discount/sponsor code. This can result in a self referential structure that does not allow the administrator to change the member's membership level from the Edit Profile page back to a Parent account.

**Comment by messica** [comment]
Another user had this problem:
**Support Ticket (Moderators Only)**:
https://www.paidmembershipspro.com/forums/topic/help-configuring-the-sponsored-group-members-plugin/

**Comment by greathmaster** [comment]
PR: https://github.com/strangerstudios/pmpro-sponsored-members/pull/51
