### ISSUE TITLE
Allow Membership Manager Role to view Sponsored section on Edit Profile

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-sponsored-members#32]
The Membership Manager role should be able to view the section related to sponsored memberships on the Edit Profile screen. We currently check for the "manage_options" capability.

https://github.com/strangerstudios/pmpro-sponsored-members/blob/master/pmpro-sponsored-members.php#L1471

https://www.paidmembershipspro.com/forums/topic/membership-manager-role-visability-of/

**Comment by andrewlimaza** [comment]
The `edit_users` as per the topic thread makes sense and seems efficient.

https://github.com/strangerstudios/pmpro-sponsored-members/pull/33
