### ISSUE TITLE
Syntax Error Line 805

### ISSUE THREAD

**Issue by itsjusteileen** [strangerstudios/pmpro-sponsored-members#42]
It looks like there is an extra class and the line should be `<div class="pmpro_checkout-field pmpro_checkout-field-seats">`

**Comment by kimcoleman** [comment]
When we removed tables from the checkout and other pages as part of the 1.9.4 release of Paid Memberships Pro, not all Add Ons that create boxes at the checkout were updated. This plugin should definitely have a pass to remove the table added to the checkout form and use the newly updated HTML structure for checkout.
