### ISSUE TITLE
Feature Request: Change default expiration of sponsor code.

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-sponsored-members#48]
A support user has requested the ability to change the expiration date of the sponsor code created at checkout. We could add a filter like pmprosm_create_sponsor_code_array to change the details of the code created during checkout.

https://github.com/strangerstudios/pmpro-sponsored-members/blob/2d9612ad4422d1f078f5dd704273b3f4b9b16f38/pmpro-sponsored-members.php#L231-L239

**Comment by greathmaster** [comment]
https://github.com/strangerstudios/pmpro-sponsored-members/pull/49

**Comment by andrewlimaza** [comment]
This has been merged in.
