### ISSUE TITLE
'Child' accounts not receiving the email.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-sponsored-members#62]
Children accounts do not receive emails when creating the child account at checkout.

Example Code For Sponsored Accounts:
`global $pmprosm_sponsored_account_levels;
$pmprosm_sponsored_account_levels = array(
	//set 5 seats at checkout
	1 => array(
		'main_level_id' => 1, //redundant but useful
        'sponsored_level_id' => array(2), //array or single id
        'seat_cost' => 5,
        'max_seats' => 5,
        'sponsored_accounts_at_checkout' => true,
	)
);
`

Code Ref: https://github.com/strangerstudios/pmpro-sponsored-members/blob/master/pmpro-sponsored-members.php#L1373-L1386

**Comment by dwcouch** [comment]
I've also experienced this. The sponsor notifications go out after checkout/registration. But the sponsored membership does not.

This is also true if the following setting is checked:

**New Users: | Default WP notification email. (Recommended: Leave unchecked. Members will still get an email confirmation from PMPro after checkout.)**

In this case the Sponsor emails are sent by both WP and PMPro, but the sponsored account sends nothing through either.

**Comment by andrewlimaza** [comment]
This looks fixed in a release that happened fairly recently. If you are still experiencing this issue, please feel free to create a new issue.
