### ISSUE TITLE
BUG: PMPro Add Member From Admin Add On – PHP Notice After Updating To v0.6

### ISSUE THREAD

**Issue by tictag** [strangerstudios/pmpro-sponsored-members#67]
**For moderators:** https://www.paidmembershipspro.com/forums/topic/bug-pmpro-add-member-from-admin-add-on-php-notice-after-updating-to-v0-6

The following PHP Notice is recorded in wp-debug log after updating Add Member From Admin Add On to v0.6 and adding a new member through the add-on.

Note: The member is added successful.

`[23-Nov-2019 17:13:41 UTC] PHP Notice: Undefined index: membership_id in /home/customer/www/dev.ksa-uk.net/public_html/wp/wp-content/plugins/pmpro-sponsored-members/pmpro-sponsored-members.php on line 1739`

Find a screenshot of the Add Member page and a relevant wp_debug.log extract attached.

PHP v7.1.33
WordPress v5.3
PMPro v2.1.4
Add Member From Admin Add On v0.6
Approvals Add On v1.3.4
Gift Aid Add On v1.2
Sponsored/Group Members Add On v0.6.3

[wp-debug.zip](https://github.com/strangerstudios/pmpro-sponsored-members/files/3898703/wp-debug.zip)
![2019-11-23_17-25-55](https://user-images.githubusercontent.com/12136834/69758135-97cee600-1156-11ea-8bec-e4b98463cafc.png)

**Comment by andrewlimaza** [comment]
This has been fixed. I have just tested v0.8
