### ISSUE TITLE
Sponsored link on Account page allows Parent to access sponsor link while signed in causing potential membership corruption.

### ISSUE THREAD

**Issue by bluesteamhost** [strangerstudios/pmpro-sponsored-members#77]
After the parent has had his/her profile approved and the Sponsor link is shown, the parent is able to access this link while logged in.  If the parent member does NOT sign out first and proceeds to complete the registration, their own profile is overwritten with the new details causing corruption of the parent membership profile.

This also completely REMOVES the sponsored links from the parent member now. This essentially damages the parent profile beyond repair.

Please also note that you might be asking yourself, "Why would the Sponsor use their own link". Well, there are times when the sponsor might want to register on behalf of their children accounts.

Here is a loom video showing the problem:
https://www.loom.com/share/f913dfe9fd85401ba32eebbb6d12dd6e

**Comment by andrewlimaza** [comment]
Hi @bluesteamhost 

This should be fixed in a pre-release of this commit -> https://github.com/strangerstudios/pmpro-sponsored-members/commit/ea74f298cd991019203078d89652d70f92cee2c4

**Comment by andrewlimaza** [comment]
This has been resolved, I have just tested and confirm it does work. If the sponsor wants to use their own code and signup on behalf of a user (child account) they would need to logout first.

![Screen Shot 2020-09-28 at 12 53 34](https://user-images.githubusercontent.com/12629136/94423927-b6907580-0189-11eb-91e0-1e55087e4804.png)

This should be released in the near future.
