### ISSUE TITLE
The `children_hide_password` attribute is not working when set to true

### ISSUE THREAD

**Issue by MaryOJob** [strangerstudios/pmpro-sponsored-members#89]
**Describe the bug**
When configuring the Sponsored Members (SM) Code, if you set the `'children_hide_password' => true,`, the password field is still shown at checkouts when the main member selects the number of seats they want.

**To Reproduce**

Setup Sponsored Members (SM) Add On to create child accounts at checkout.
Be sure to set the `'children_hide_password' => true,`
Go to checkout, select your seats, the password field stays despite setting it up to not show in the SM code

Isolating the problem (mark completed items with an [x]):

[x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin and Sponsored Members Add On is active.
[x] This bug happens with a default WordPress theme active, or Memberlite.
[x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WP Version 5.6
PHP Version 7.2.9
PMPro SM Version 0.10
PMPro Version 2.5.2
```
</details>

For moderators only: https://www.paidmembershipspro.com/forums/topic/sponsor-levels-password-not-hiding/

**Comment by kimwhite** [comment]
I have tested and sometimes it does hide, however it's still required.
